### PR TITLE
Using instance id for connection to unleash server

### PR DESCRIPTION
**Pull request by webii**

### CODE REVIEW

**Comment by ivarconr** [comment]
@webii do you want to resolve the feedbacks or do you want us to take it over and complete this PR?

**Comment by webii** [comment]
@ivarconr I can resolve the feedback by myself, but I don't see any comments by now.

**Comment by ivarconr** [comment]
> @ivarconr I can resolve the feedback by myself, but I don't see any comments by now.

They where all pending

**Comment by jat10** [comment]
Hey guys, when this PR will get merged?

**Comment by ivarconr** [comment]
Hi, @jat10 @webii 

I took the liberty to create a PR based on the suggestion here to make progress, see #19

**Comment by ivarconr** [comment]
@jat10 released as part of 0.2.0.

**Comment by jat10** [comment]
@ivarconr thank you. I will check it

**Pull request closed without merging**
